[commands.settings]
    command_prefix = "!"

#[commands.bindings.ping]
#    alias = "ping"
#    permission = "basic.ping"
#    executor = "com.github.psygate.discord.owlbot.commands.PingCommand"
